name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hello @${{ github.actor }}!  

            Thank you for raising an issue in the **DK24 - Community Website** repository. 

            We’re excited to have you contribute to our mission of **Connecting College Tech Communities** — fostering collaboration, learning, and building together in public. 

            ---

            ### Before You Proceed:  
            1. **Check for Duplicates**: Ensure this issue hasn't already been reported or addressed.  
            2. **Add Relevant Labels**: Use appropriate labels like `bug`, `enhancement`, or `documentation` to categorize the issue.  
            3. **Assign a Responsible Member**: Tag a team member to facilitate quick resolution.  
            
            Happy coding! 😊
          pr-message: |
            🙌 Welcome @${{ github.actor }}!  

            Thank you for contributing to the **DK24 - Community Website** 💻. This platform connects college tech communities to learn and grow together.  

            Your pull request will be reviewed soon. Please ensure it follows our **guidelines** and includes appropriate labels like `feature`, `fix`, or `refactor`.  

            Together, let’s build something amazing! 🚀  
