name: pull requests

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  uneditable:
    uses: Developer-Kommunity-24/community-website/.github/workflows/pull-requests.yml@main